name: filmle
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  http: ^0.13.5
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  video_player: ^2.5.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  
  assets:
    - assets/images/


